# Generated by Django 4.2.4 on 2023-08-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_venta',
            field=models.IntegerField(),
        ),
    ]
